<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Anmelden',
        'headline' => 'Anmelden',
        'subheadline' => 'Login to your account below',
        'show_subheadline' => false,
        'email_address' => 'E-Mail Adresse',
        'password' => 'Passwort',
        'remember_me' => 'Zugangsdaten speichern',
        'edit' => 'Bearbeiten',
        'button' => 'Weiter',
        'forget_password' => 'Passwort vergessen?',
        'dont_have_an_account' => 'Noch kein Account?',
        'sign_up' => 'Registrieren',
        'social_auth_authenticated_message' => 'Sie sind über __social_providers_list__ authentifiziert worden. Bitte melden Sie sich unten bei diesem Netzwerk an.',
        'change_email' => 'E-Mail Adresse ändern',
        'couldnt_find_your_account' => 'Konnte Ihr Konto nicht finden',
    ],
    'register' => [
        'page_title' => 'Sign up',
        'headline' => 'Registrieren',
        'subheadline' => 'Register for your free account below.',
        'show_subheadline' => false,
        'name' => 'Name',
        'email_address' => 'E-Mail Adresse',
        'password' => 'Passwort',
        'password_confirmation' => 'Passwort bestätigung',
        'already_have_an_account' => 'Sie haben bereits ein Konto?',
        'sign_in' => 'Anmelden',
        'button' => 'Weiter',
        'email_registration_disabled' => 'Die E-Mail-Registrierung ist derzeit deaktiviert. Bitte verwenden Sie die soziale Anmeldung.',
    ],
    'verify' => [
        'page_title' => 'Bestätigen Sie Ihren Account',
        'headline' => 'Bestätigen Sie Ihre E-Mail Adresse',
        'subheadline' => 'Bevor Sie fortfahren können, müssen Sie Ihre E-Mail verifizieren.',
        'show_subheadline' => false,
        'description' => 'Bevor Sie fortfahren, überprüfen Sie bitte Ihre E-Mail auf einen Bestätigungslink. Wenn Sie die E-Mail nicht erhalten haben,',
        'new_request_link' => 'click here to request another',
        'new_link_sent' => 'Klicken Sie hier, um ein weiteres Exemplar anzufordern',
        'or' => 'Oder',
        'logout' => 'Abmelden',
    ],
    'passwordConfirm' => [
        'page_title' => 'Passwort bestätigen',
        'headline' => 'Passwort bestätigen',
        'subheadline' => 'Stellen Sie sicher, dass Sie Ihr Passwort unten bestätigen',
        'show_subheadline' => false,
        'password' => 'Passwort',
        'button' => 'Passwort bestätigen',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Passwort zurücksetzen anfordern',
        'headline' => 'Passwort zurücksetzen',
        'subheadline' => 'Geben Sie unten Ihre E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen',
        'show_subheadline' => false,
        'email' => 'E-Mail Adresse',
        'button' => 'E-Mail zum zürücksetzen senden',
        'or' => 'oder',
        'return_to_login' => 'Zurück zum Anmelden',
    ],
    'passwordReset' => [
        'page_title' => 'Passwort zurücksetzen',
        'headline' => 'Passwort zurücksetzen',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'E-Mail Adresse',
        'password' => 'Passwort',
        'password_confirm' => 'Passwort bestätigen',
        'button' => 'Passwort zurücksetzen',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
